name: CI
"on":
  push:
    paths-ignore:
    - '**.md'
    - docs/**
  pull_request:
    paths-ignore:
    - '**.md'
    - docs/**
env:
  CI: "true"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - 11.x
        - 12.x
        - 14.x
        os:
        - ubuntu-latest
    name: Node ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
      id: d7a5459c-99f9-4016-9528-0ec359197b6e
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        yarn install
    - name: test
      run: yarn test
