name: wedwedewdew
"on":
    push:
        paths-ignore:
            - '**.md'
            - docs/**
    pull_request:
        paths-ignore:
            - '**.md'
            - docs/**
env:
    A: e429af8e-784e-4f46-a534-bb0535610ad3
    B: StarpTech/shikaka
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version:
                    - 12.x
                    - 13.x
                    - 14.x
                os:
                    - ubuntu-latest
        name: Node ${{ matrix.node-version }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              name: Use Node.js ${{ matrix.node-version }}
              with:
                node-version: ${{ matrix.node-version }}
            - name: install
              run: yarn install
        needs:
            - a
